# Generated by Django 5.2.16 on 2026-07-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('roll_no', models.CharField(max_length=30)),
                ('student_name', models.CharField(max_length=150)),
                ('campus', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=11)),
                ('total_marks', models.PositiveIntegerField()),
                ('obtained_marks', models.PositiveIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-percentage'],
            },
        ),
    ]
